pathology:
    resource: "@PathologyBundle/Resources/config/routing.yml"
    prefix:   /

logout:
    path: /logout

login_route:
    path: /login
    defaults: { _controller: PathologyBundle:Security:login}

login_check:
    path: /login_check
    defaults: { _controller: PathologyBundle:Security:loginCheck}
