<?php

namespace PathologyBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PathologyTestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PathologyTestRepository extends EntityRepository
{
}
