<?php

namespace PathologyBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ReportRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReportRepository extends EntityRepository
{
    public function findReportsByPatient($patient)
    {
        return $this->findBy(array('patient' => $patient->getId()));
    }
}
