<?php

namespace PathologyBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    /**
     * Find users by role
     */
    public function findUsersByRole($role)
    {
        return $this->findBy(array('role' => $role));
    }
}
